// Configuración central de categorías del sector salud
// (excluye farmacias y hospitales públicos, que ya tienen su propia ruta)

export type HealthCategory = {
  slug: string;
  label: string;
  shortLabel?: string;
  emoji: string; // símbolo visible en tiles
  query: string; // query para Google Places
  // Tonos (oklch) para el dashboard
  bg: string;
  fg: string;
  // Gradiente de fondo (tailwind-friendly hex)
  gradFrom: string;
  gradVia: string;
  gradTo: string;
  accent: string; // color principal (hex)
  group: "publico" | "privado";
  description: string;
};

export const HEALTH_CATEGORIES: HealthCategory[] = [
  // --- PÚBLICO ---
  {
    slug: "centros-salud",
    label: "Centros de salud",
    emoji: "🏨",
    query: "centro de salud Alicante",
    bg: "oklch(0.94 0.07 145)",
    fg: "oklch(0.45 0.15 150)",
    gradFrom: "#022c22",
    gradVia: "#064e3b",
    gradTo: "#052e2b",
    accent: "#10b981",
    group: "publico",
    description: "Atención primaria pública",
  },
  {
    slug: "especialidades",
    label: "Especialidades",
    emoji: "🩺",
    query: "consultas externas especialidades Alicante",
    bg: "oklch(0.94 0.07 220)",
    fg: "oklch(0.48 0.16 230)",
    gradFrom: "#0c2340",
    gradVia: "#1a4a6e",
    gradTo: "#0a1f33",
    accent: "#38bdf8",
    group: "publico",
    description: "Consultas de especialidades",
  },
  {
    slug: "urgencias",
    label: "Urgencias",
    emoji: "🚑",
    query: "urgencias hospital Alicante",
    bg: "oklch(0.93 0.10 28)",
    fg: "oklch(0.50 0.20 28)",
    gradFrom: "#3f0d0d",
    gradVia: "#7f1d1d",
    gradTo: "#450a0a",
    accent: "#ef4444",
    group: "publico",
    description: "PAC, SAMU y urgencias hospitalarias",
  },
  {
    slug: "salud-mental",
    label: "Salud mental",
    emoji: "🧠",
    query: "unidad salud mental Alicante",
    bg: "oklch(0.93 0.07 290)",
    fg: "oklch(0.48 0.16 290)",
    gradFrom: "#1e1b4b",
    gradVia: "#3730a3",
    gradTo: "#1e1b4b",
    accent: "#a78bfa",
    group: "publico",
    description: "Unidades de salud mental",
  },
  {
    slug: "admin-sip",
    label: "Administración SIP",
    emoji: "📋",
    query: "centro salud SIP tarjeta sanitaria Alicante",
    bg: "oklch(0.94 0.05 80)",
    fg: "oklch(0.45 0.12 80)",
    gradFrom: "#3b2f0a",
    gradVia: "#78521a",
    gradTo: "#3b2f0a",
    accent: "#eab308",
    group: "publico",
    description: "Cita previa y tarjeta sanitaria",
  },

  // --- PRIVADO ---
  {
    slug: "hospitales-privados",
    label: "Hospitales privados",
    emoji: "🏥",
    query: "hospital privado Alicante",
    bg: "oklch(0.94 0.07 340)",
    fg: "oklch(0.50 0.18 350)",
    gradFrom: "#3a0a23",
    gradVia: "#831843",
    gradTo: "#4a1238",
    accent: "#f472b6",
    group: "privado",
    description: "Vithas, Quirón, HLA, IMED…",
  },
  {
    slug: "odontologia",
    label: "Odontología",
    emoji: "🦷",
    query: "clínica dental Alicante",
    bg: "oklch(0.94 0.06 200)",
    fg: "oklch(0.45 0.14 210)",
    gradFrom: "#0c2c34",
    gradVia: "#155e75",
    gradTo: "#082f3a",
    accent: "#22d3ee",
    group: "privado",
    description: "Dentistas y clínicas dentales",
  },
  {
    slug: "opticas",
    label: "Ópticas",
    emoji: "👓",
    query: "óptica Alicante",
    bg: "oklch(0.94 0.07 250)",
    fg: "oklch(0.48 0.16 255)",
    gradFrom: "#1e1b4b",
    gradVia: "#3730a3",
    gradTo: "#1e1b4b",
    accent: "#818cf8",
    group: "privado",
    description: "Gafas, lentes y revisiones",
  },
  {
    slug: "rehabilitacion",
    label: "Rehabilitación",
    emoji: "🤸",
    query: "fisioterapia rehabilitación Alicante",
    bg: "oklch(0.94 0.08 60)",
    fg: "oklch(0.50 0.16 55)",
    gradFrom: "#3b1d0a",
    gradVia: "#7c2d12",
    gradTo: "#431407",
    accent: "#fb923c",
    group: "privado",
    description: "Fisioterapia y recuperación",
  },
  {
    slug: "psicologia",
    label: "Psicología",
    emoji: "🧠",
    query: "psicólogo consulta Alicante",
    bg: "oklch(0.94 0.06 300)",
    fg: "oklch(0.48 0.15 300)",
    gradFrom: "#2e1065",
    gradVia: "#6d28d9",
    gradTo: "#1e1b4b",
    accent: "#c084fc",
    group: "privado",
    description: "Consultas privadas",
  },
  {
    slug: "terapia-familiar",
    label: "Terapia familiar",
    emoji: "👨‍👩‍👧",
    query: "terapia familiar pareja Alicante",
    bg: "oklch(0.94 0.07 320)",
    fg: "oklch(0.48 0.16 320)",
    gradFrom: "#3b0a2e",
    gradVia: "#9d174d",
    gradTo: "#4a0a32",
    accent: "#f9a8d4",
    group: "privado",
    description: "Pareja, familia y mediación",
  },
  {
    slug: "pediatria-privada",
    label: "Pediatría privada",
    emoji: "👶",
    query: "pediatra privado Alicante",
    bg: "oklch(0.94 0.08 40)",
    fg: "oklch(0.55 0.16 40)",
    gradFrom: "#3b1d0a",
    gradVia: "#92400e",
    gradTo: "#431407",
    accent: "#fbbf24",
    group: "privado",
    description: "Pediatras y clínicas infantiles",
  },
  {
    slug: "ginecologia",
    label: "Ginecología",
    emoji: "🤰",
    query: "ginecólogo clínica Alicante",
    bg: "oklch(0.94 0.07 350)",
    fg: "oklch(0.50 0.17 355)",
    gradFrom: "#3b0a23",
    gradVia: "#9f1239",
    gradTo: "#4a1238",
    accent: "#fb7185",
    group: "privado",
    description: "Obstetricia y salud de la mujer",
  },
  {
    slug: "analisis-clinicos",
    label: "Análisis clínicos",
    emoji: "💉",
    query: "laboratorio análisis clínicos Alicante",
    bg: "oklch(0.94 0.05 180)",
    fg: "oklch(0.45 0.13 190)",
    gradFrom: "#042f2e",
    gradVia: "#115e59",
    gradTo: "#042f2e",
    accent: "#5eead4",
    group: "privado",
    description: "Laboratorios y extracciones",
  },
  {
    slug: "diagnostico-imagen",
    label: "Diagnóstico por imagen",
    emoji: "🩻",
    query: "centro radiología imagen médica Alicante",
    bg: "oklch(0.94 0.04 230)",
    fg: "oklch(0.45 0.12 235)",
    gradFrom: "#0c1a2e",
    gradVia: "#1e3a8a",
    gradTo: "#0a1326",
    accent: "#60a5fa",
    group: "privado",
    description: "Radiología, RMN, ecografías",
  },
  {
    slug: "audiologia",
    label: "Audiología",
    emoji: "🦻",
    query: "audífonos audiología Alicante",
    bg: "oklch(0.94 0.05 100)",
    fg: "oklch(0.48 0.13 100)",
    gradFrom: "#1a2e05",
    gradVia: "#365314",
    gradTo: "#1a2e05",
    accent: "#bef264",
    group: "privado",
    description: "Audífonos y otorrinos",
  },
  {
    slug: "nutricion",
    label: "Nutrición y dietética",
    emoji: "🥗",
    query: "nutricionista dietista Alicante",
    bg: "oklch(0.94 0.09 130)",
    fg: "oklch(0.48 0.16 135)",
    gradFrom: "#052e16",
    gradVia: "#166534",
    gradTo: "#052e16",
    accent: "#86efac",
    group: "privado",
    description: "Dietistas-nutricionistas",
  },
  {
    slug: "estetica-medica",
    label: "Estética médica",
    emoji: "💆",
    query: "medicina estética clínica Alicante",
    bg: "oklch(0.94 0.07 15)",
    fg: "oklch(0.50 0.16 15)",
    gradFrom: "#3b0a0a",
    gradVia: "#9f1239",
    gradTo: "#4a0a0a",
    accent: "#f9a8d4",
    group: "privado",
    description: "Dermoestética y medicina estética",
  },
  {
    slug: "traumatologia",
    label: "Traumatología privada",
    emoji: "🦴",
    query: "traumatólogo clínica Alicante",
    bg: "oklch(0.94 0.05 50)",
    fg: "oklch(0.48 0.13 50)",
    gradFrom: "#27170c",
    gradVia: "#78350f",
    gradTo: "#27170c",
    accent: "#fbbf24",
    group: "privado",
    description: "Lesiones y cirugía ortopédica",
  },
  {
    slug: "cardiologia",
    label: "Cardiología privada",
    emoji: "❤️",
    query: "cardiólogo clínica Alicante",
    bg: "oklch(0.93 0.10 25)",
    fg: "oklch(0.50 0.20 25)",
    gradFrom: "#3f0d0d",
    gradVia: "#991b1b",
    gradTo: "#450a0a",
    accent: "#f87171",
    group: "privado",
    description: "Pruebas y consultas cardiológicas",
  },
  {
    slug: "oftalmologia",
    label: "Oftalmología",
    emoji: "👁️",
    query: "oftalmólogo clínica Alicante",
    bg: "oklch(0.94 0.06 240)",
    fg: "oklch(0.48 0.15 245)",
    gradFrom: "#0c1a3e",
    gradVia: "#1e40af",
    gradTo: "#0a1326",
    accent: "#93c5fd",
    group: "privado",
    description: "Cirugía ocular y revisiones",
  },
  {
    slug: "vacunacion",
    label: "Vacunación",
    emoji: "💉",
    query: "vacunación internacional Alicante",
    bg: "oklch(0.94 0.07 165)",
    fg: "oklch(0.48 0.15 170)",
    gradFrom: "#042f2e",
    gradVia: "#0f766e",
    gradTo: "#042f2e",
    accent: "#2dd4bf",
    group: "privado",
    description: "Centros de vacunación internacional",
  },
  {
    slug: "veterinarios",
    label: "Veterinarios",
    emoji: "🐾",
    query: "veterinario clínica Alicante",
    bg: "oklch(0.94 0.07 70)",
    fg: "oklch(0.48 0.15 70)",
    gradFrom: "#27170c",
    gradVia: "#92400e",
    gradTo: "#27170c",
    accent: "#fbbf24",
    group: "privado",
    description: "Clínicas y urgencias 24h",
  },
];

export function getCategory(slug: string): HealthCategory | undefined {
  return HEALTH_CATEGORIES.find((c) => c.slug === slug);
}
