project_id = "htzatsqihojttrwsawis"

[functions.chat]
verify_jwt = false

[functions.bus-eta]
verify_jwt = false

[functions.bus-eta-raw]
verify_jwt = false

[functions.trenes-sync]
verify_jwt = false
