/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StayRouteImport } from './routes/stay'
import { Route as RepoRouteImport } from './routes/repo'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as EatRouteImport } from './routes/eat'
import { Route as BusinessRouteImport } from './routes/business'
import { Route as BusRouteImport } from './routes/bus'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BusinessIndexRouteImport } from './routes/business.index'
import { Route as BusinessReferralsRouteImport } from './routes/business.referrals'
import { Route as BusinessQrRouteImport } from './routes/business.qr'
import { Route as BusinessOnboardingRouteImport } from './routes/business.onboarding'
import { Route as BusinessMetricsRouteImport } from './routes/business.metrics'
import { Route as BusinessLoginRouteImport } from './routes/business.login'
import { Route as BusinessBookingsRouteImport } from './routes/business.bookings'
import { Route as BusPlannerRouteImport } from './routes/bus.planner'
import { Route as BusLinesRouteImport } from './routes/bus.lines'
import { Route as BusLinesCodeRouteImport } from './routes/bus.lines.$code'
import { Route as ApiPublicQrValidateRouteImport } from './routes/api/public/qr-validate'
import { Route as ApiPublicBusEtaRouteImport } from './routes/api/public/bus-eta'
import { Route as ApiPublicBookingCreateRouteImport } from './routes/api/public/booking-create'

const StayRoute = StayRouteImport.update({
  id: '/stay',
  path: '/stay',
  getParentRoute: () => rootRouteImport,
} as any)
const RepoRoute = RepoRouteImport.update({
  id: '/repo',
  path: '/repo',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const EatRoute = EatRouteImport.update({
  id: '/eat',
  path: '/eat',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessRoute = BusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => rootRouteImport,
} as any)
const BusRoute = BusRouteImport.update({
  id: '/bus',
  path: '/bus',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessIndexRoute = BusinessIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BusinessRoute,
} as any)
const BusinessReferralsRoute = BusinessReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => BusinessRoute,
} as any)
const BusinessQrRoute = BusinessQrRouteImport.update({
  id: '/qr',
  path: '/qr',
  getParentRoute: () => BusinessRoute,
} as any)
const BusinessOnboardingRoute = BusinessOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => BusinessRoute,
} as any)
const BusinessMetricsRoute = BusinessMetricsRouteImport.update({
  id: '/metrics',
  path: '/metrics',
  getParentRoute: () => BusinessRoute,
} as any)
const BusinessLoginRoute = BusinessLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => BusinessRoute,
} as any)
const BusinessBookingsRoute = BusinessBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => BusinessRoute,
} as any)
const BusPlannerRoute = BusPlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => BusRoute,
} as any)
const BusLinesRoute = BusLinesRouteImport.update({
  id: '/lines',
  path: '/lines',
  getParentRoute: () => BusRoute,
} as any)
const BusLinesCodeRoute = BusLinesCodeRouteImport.update({
  id: '/$code',
  path: '/$code',
  getParentRoute: () => BusLinesRoute,
} as any)
const ApiPublicQrValidateRoute = ApiPublicQrValidateRouteImport.update({
  id: '/api/public/qr-validate',
  path: '/api/public/qr-validate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBusEtaRoute = ApiPublicBusEtaRouteImport.update({
  id: '/api/public/bus-eta',
  path: '/api/public/bus-eta',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBookingCreateRoute = ApiPublicBookingCreateRouteImport.update({
  id: '/api/public/booking-create',
  path: '/api/public/booking-create',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bus': typeof BusRouteWithChildren
  '/business': typeof BusinessRouteWithChildren
  '/eat': typeof EatRoute
  '/explore': typeof ExploreRoute
  '/login': typeof LoginRoute
  '/perfil': typeof PerfilRoute
  '/repo': typeof RepoRoute
  '/stay': typeof StayRoute
  '/bus/lines': typeof BusLinesRouteWithChildren
  '/bus/planner': typeof BusPlannerRoute
  '/business/bookings': typeof BusinessBookingsRoute
  '/business/login': typeof BusinessLoginRoute
  '/business/metrics': typeof BusinessMetricsRoute
  '/business/onboarding': typeof BusinessOnboardingRoute
  '/business/qr': typeof BusinessQrRoute
  '/business/referrals': typeof BusinessReferralsRoute
  '/business/': typeof BusinessIndexRoute
  '/api/public/booking-create': typeof ApiPublicBookingCreateRoute
  '/api/public/bus-eta': typeof ApiPublicBusEtaRoute
  '/api/public/qr-validate': typeof ApiPublicQrValidateRoute
  '/bus/lines/$code': typeof BusLinesCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bus': typeof BusRouteWithChildren
  '/eat': typeof EatRoute
  '/explore': typeof ExploreRoute
  '/login': typeof LoginRoute
  '/perfil': typeof PerfilRoute
  '/repo': typeof RepoRoute
  '/stay': typeof StayRoute
  '/bus/lines': typeof BusLinesRouteWithChildren
  '/bus/planner': typeof BusPlannerRoute
  '/business/bookings': typeof BusinessBookingsRoute
  '/business/login': typeof BusinessLoginRoute
  '/business/metrics': typeof BusinessMetricsRoute
  '/business/onboarding': typeof BusinessOnboardingRoute
  '/business/qr': typeof BusinessQrRoute
  '/business/referrals': typeof BusinessReferralsRoute
  '/business': typeof BusinessIndexRoute
  '/api/public/booking-create': typeof ApiPublicBookingCreateRoute
  '/api/public/bus-eta': typeof ApiPublicBusEtaRoute
  '/api/public/qr-validate': typeof ApiPublicQrValidateRoute
  '/bus/lines/$code': typeof BusLinesCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bus': typeof BusRouteWithChildren
  '/business': typeof BusinessRouteWithChildren
  '/eat': typeof EatRoute
  '/explore': typeof ExploreRoute
  '/login': typeof LoginRoute
  '/perfil': typeof PerfilRoute
  '/repo': typeof RepoRoute
  '/stay': typeof StayRoute
  '/bus/lines': typeof BusLinesRouteWithChildren
  '/bus/planner': typeof BusPlannerRoute
  '/business/bookings': typeof BusinessBookingsRoute
  '/business/login': typeof BusinessLoginRoute
  '/business/metrics': typeof BusinessMetricsRoute
  '/business/onboarding': typeof BusinessOnboardingRoute
  '/business/qr': typeof BusinessQrRoute
  '/business/referrals': typeof BusinessReferralsRoute
  '/business/': typeof BusinessIndexRoute
  '/api/public/booking-create': typeof ApiPublicBookingCreateRoute
  '/api/public/bus-eta': typeof ApiPublicBusEtaRoute
  '/api/public/qr-validate': typeof ApiPublicQrValidateRoute
  '/bus/lines/$code': typeof BusLinesCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bus'
    | '/business'
    | '/eat'
    | '/explore'
    | '/login'
    | '/perfil'
    | '/repo'
    | '/stay'
    | '/bus/lines'
    | '/bus/planner'
    | '/business/bookings'
    | '/business/login'
    | '/business/metrics'
    | '/business/onboarding'
    | '/business/qr'
    | '/business/referrals'
    | '/business/'
    | '/api/public/booking-create'
    | '/api/public/bus-eta'
    | '/api/public/qr-validate'
    | '/bus/lines/$code'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bus'
    | '/eat'
    | '/explore'
    | '/login'
    | '/perfil'
    | '/repo'
    | '/stay'
    | '/bus/lines'
    | '/bus/planner'
    | '/business/bookings'
    | '/business/login'
    | '/business/metrics'
    | '/business/onboarding'
    | '/business/qr'
    | '/business/referrals'
    | '/business'
    | '/api/public/booking-create'
    | '/api/public/bus-eta'
    | '/api/public/qr-validate'
    | '/bus/lines/$code'
  id:
    | '__root__'
    | '/'
    | '/bus'
    | '/business'
    | '/eat'
    | '/explore'
    | '/login'
    | '/perfil'
    | '/repo'
    | '/stay'
    | '/bus/lines'
    | '/bus/planner'
    | '/business/bookings'
    | '/business/login'
    | '/business/metrics'
    | '/business/onboarding'
    | '/business/qr'
    | '/business/referrals'
    | '/business/'
    | '/api/public/booking-create'
    | '/api/public/bus-eta'
    | '/api/public/qr-validate'
    | '/bus/lines/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BusRoute: typeof BusRouteWithChildren
  BusinessRoute: typeof BusinessRouteWithChildren
  EatRoute: typeof EatRoute
  ExploreRoute: typeof ExploreRoute
  LoginRoute: typeof LoginRoute
  PerfilRoute: typeof PerfilRoute
  RepoRoute: typeof RepoRoute
  StayRoute: typeof StayRoute
  ApiPublicBookingCreateRoute: typeof ApiPublicBookingCreateRoute
  ApiPublicBusEtaRoute: typeof ApiPublicBusEtaRoute
  ApiPublicQrValidateRoute: typeof ApiPublicQrValidateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stay': {
      id: '/stay'
      path: '/stay'
      fullPath: '/stay'
      preLoaderRoute: typeof StayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repo': {
      id: '/repo'
      path: '/repo'
      fullPath: '/repo'
      preLoaderRoute: typeof RepoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eat': {
      id: '/eat'
      path: '/eat'
      fullPath: '/eat'
      preLoaderRoute: typeof EatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business': {
      id: '/business'
      path: '/business'
      fullPath: '/business'
      preLoaderRoute: typeof BusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bus': {
      id: '/bus'
      path: '/bus'
      fullPath: '/bus'
      preLoaderRoute: typeof BusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/': {
      id: '/business/'
      path: '/'
      fullPath: '/business/'
      preLoaderRoute: typeof BusinessIndexRouteImport
      parentRoute: typeof BusinessRoute
    }
    '/business/referrals': {
      id: '/business/referrals'
      path: '/referrals'
      fullPath: '/business/referrals'
      preLoaderRoute: typeof BusinessReferralsRouteImport
      parentRoute: typeof BusinessRoute
    }
    '/business/qr': {
      id: '/business/qr'
      path: '/qr'
      fullPath: '/business/qr'
      preLoaderRoute: typeof BusinessQrRouteImport
      parentRoute: typeof BusinessRoute
    }
    '/business/onboarding': {
      id: '/business/onboarding'
      path: '/onboarding'
      fullPath: '/business/onboarding'
      preLoaderRoute: typeof BusinessOnboardingRouteImport
      parentRoute: typeof BusinessRoute
    }
    '/business/metrics': {
      id: '/business/metrics'
      path: '/metrics'
      fullPath: '/business/metrics'
      preLoaderRoute: typeof BusinessMetricsRouteImport
      parentRoute: typeof BusinessRoute
    }
    '/business/login': {
      id: '/business/login'
      path: '/login'
      fullPath: '/business/login'
      preLoaderRoute: typeof BusinessLoginRouteImport
      parentRoute: typeof BusinessRoute
    }
    '/business/bookings': {
      id: '/business/bookings'
      path: '/bookings'
      fullPath: '/business/bookings'
      preLoaderRoute: typeof BusinessBookingsRouteImport
      parentRoute: typeof BusinessRoute
    }
    '/bus/planner': {
      id: '/bus/planner'
      path: '/planner'
      fullPath: '/bus/planner'
      preLoaderRoute: typeof BusPlannerRouteImport
      parentRoute: typeof BusRoute
    }
    '/bus/lines': {
      id: '/bus/lines'
      path: '/lines'
      fullPath: '/bus/lines'
      preLoaderRoute: typeof BusLinesRouteImport
      parentRoute: typeof BusRoute
    }
    '/bus/lines/$code': {
      id: '/bus/lines/$code'
      path: '/$code'
      fullPath: '/bus/lines/$code'
      preLoaderRoute: typeof BusLinesCodeRouteImport
      parentRoute: typeof BusLinesRoute
    }
    '/api/public/qr-validate': {
      id: '/api/public/qr-validate'
      path: '/api/public/qr-validate'
      fullPath: '/api/public/qr-validate'
      preLoaderRoute: typeof ApiPublicQrValidateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bus-eta': {
      id: '/api/public/bus-eta'
      path: '/api/public/bus-eta'
      fullPath: '/api/public/bus-eta'
      preLoaderRoute: typeof ApiPublicBusEtaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/booking-create': {
      id: '/api/public/booking-create'
      path: '/api/public/booking-create'
      fullPath: '/api/public/booking-create'
      preLoaderRoute: typeof ApiPublicBookingCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BusLinesRouteChildren {
  BusLinesCodeRoute: typeof BusLinesCodeRoute
}

const BusLinesRouteChildren: BusLinesRouteChildren = {
  BusLinesCodeRoute: BusLinesCodeRoute,
}

const BusLinesRouteWithChildren = BusLinesRoute._addFileChildren(
  BusLinesRouteChildren,
)

interface BusRouteChildren {
  BusLinesRoute: typeof BusLinesRouteWithChildren
  BusPlannerRoute: typeof BusPlannerRoute
}

const BusRouteChildren: BusRouteChildren = {
  BusLinesRoute: BusLinesRouteWithChildren,
  BusPlannerRoute: BusPlannerRoute,
}

const BusRouteWithChildren = BusRoute._addFileChildren(BusRouteChildren)

interface BusinessRouteChildren {
  BusinessBookingsRoute: typeof BusinessBookingsRoute
  BusinessLoginRoute: typeof BusinessLoginRoute
  BusinessMetricsRoute: typeof BusinessMetricsRoute
  BusinessOnboardingRoute: typeof BusinessOnboardingRoute
  BusinessQrRoute: typeof BusinessQrRoute
  BusinessReferralsRoute: typeof BusinessReferralsRoute
  BusinessIndexRoute: typeof BusinessIndexRoute
}

const BusinessRouteChildren: BusinessRouteChildren = {
  BusinessBookingsRoute: BusinessBookingsRoute,
  BusinessLoginRoute: BusinessLoginRoute,
  BusinessMetricsRoute: BusinessMetricsRoute,
  BusinessOnboardingRoute: BusinessOnboardingRoute,
  BusinessQrRoute: BusinessQrRoute,
  BusinessReferralsRoute: BusinessReferralsRoute,
  BusinessIndexRoute: BusinessIndexRoute,
}

const BusinessRouteWithChildren = BusinessRoute._addFileChildren(
  BusinessRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BusRoute: BusRouteWithChildren,
  BusinessRoute: BusinessRouteWithChildren,
  EatRoute: EatRoute,
  ExploreRoute: ExploreRoute,
  LoginRoute: LoginRoute,
  PerfilRoute: PerfilRoute,
  RepoRoute: RepoRoute,
  StayRoute: StayRoute,
  ApiPublicBookingCreateRoute: ApiPublicBookingCreateRoute,
  ApiPublicBusEtaRoute: ApiPublicBusEtaRoute,
  ApiPublicQrValidateRoute: ApiPublicQrValidateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
