/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StayRouteImport } from './routes/stay'
import { Route as RepoRouteImport } from './routes/repo'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as EatRouteImport } from './routes/eat'
import { Route as IndexRouteImport } from './routes/index'

const StayRoute = StayRouteImport.update({
  id: '/stay',
  path: '/stay',
  getParentRoute: () => rootRouteImport,
} as any)
const RepoRoute = RepoRouteImport.update({
  id: '/repo',
  path: '/repo',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const EatRoute = EatRouteImport.update({
  id: '/eat',
  path: '/eat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/eat': typeof EatRoute
  '/explore': typeof ExploreRoute
  '/login': typeof LoginRoute
  '/perfil': typeof PerfilRoute
  '/repo': typeof RepoRoute
  '/stay': typeof StayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/eat': typeof EatRoute
  '/explore': typeof ExploreRoute
  '/login': typeof LoginRoute
  '/perfil': typeof PerfilRoute
  '/repo': typeof RepoRoute
  '/stay': typeof StayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/eat': typeof EatRoute
  '/explore': typeof ExploreRoute
  '/login': typeof LoginRoute
  '/perfil': typeof PerfilRoute
  '/repo': typeof RepoRoute
  '/stay': typeof StayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/eat'
    | '/explore'
    | '/login'
    | '/perfil'
    | '/repo'
    | '/stay'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/eat' | '/explore' | '/login' | '/perfil' | '/repo' | '/stay'
  id:
    | '__root__'
    | '/'
    | '/eat'
    | '/explore'
    | '/login'
    | '/perfil'
    | '/repo'
    | '/stay'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EatRoute: typeof EatRoute
  ExploreRoute: typeof ExploreRoute
  LoginRoute: typeof LoginRoute
  PerfilRoute: typeof PerfilRoute
  RepoRoute: typeof RepoRoute
  StayRoute: typeof StayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stay': {
      id: '/stay'
      path: '/stay'
      fullPath: '/stay'
      preLoaderRoute: typeof StayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repo': {
      id: '/repo'
      path: '/repo'
      fullPath: '/repo'
      preLoaderRoute: typeof RepoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eat': {
      id: '/eat'
      path: '/eat'
      fullPath: '/eat'
      preLoaderRoute: typeof EatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EatRoute: EatRoute,
  ExploreRoute: ExploreRoute,
  LoginRoute: LoginRoute,
  PerfilRoute: PerfilRoute,
  RepoRoute: RepoRoute,
  StayRoute: StayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
